process: investigate_malware
activities:

    first_alert_evaluation:
        type: sub
        activities:
            gather_alert_data: #module
                type: manual
            check_announced_changes: #module
                type: manual

    check_if_mapped_to_change:
        type: sub
        activities:
            check_if_alert_mapped_to_change:
                type: xgw
                goto:
                    - if: alert_mapped_to_change = true
                    - if: alert_mapped_to_change = false
                      then: known_false_positives
            known_false_positives: #module
                type: manual
    
    check_for_false_positive_alert:
        type: sub
        activities:
            check_if_alert_is_false_positive:
                type: xgw
                goto:
                    - if: false_positive = true
                      then: communicate_false_positive
                    - if: false_positive = false
            communicate_false_positive: #module
                type: send

    analyse_malicious_indicators:
        type: sub 
        activities:
            investigate_alert: #module
                type: manual
            gather_possible_malware_indicator: #module
                type: manual
            evaluate_possible_malware_indicator: #module
                type: manual

    check_false_positive:
        type: sub 
        activities:
            check_false_positive_and_evaluation_result:
                type: xgw 
                goto: 
                    - if: false_positive = true and evaluation_result = benign 
                      then: false_positive_alert
                    - if: false_positive = false
                      then: check_critical_alert
            false_positive_alert: #loop to "check_for_false_positive_alert" is needed here, but can't be depicted by BPMNator Online
                type: manual
                #goto: check_for_false_positive_alert
            check_critical_alert: #module
                type: manual

    check_office_hours_communication:
        type: sub
        activities:
            check_for_current_time:
                type: xgw
                goto:
                    - if: current_data_time during work hours # operator TBD
                      then: communicate_true_positive_consult
                    - if: current_data_time not during work hours
                      then: check_if_alert_critical
            check_if_alert_critical:
                type: xgw
                goto:
                    - if: critical_alert = true
                      then: communicate_true_positive_consult
                    - if: critical_alert = false
            communicate_true_positive_consult: #module
                type: send
