name: CI and Release

on:
  push:
    tags:
      - 'v[0-9]+.*' # Triggers the workflow when pushing a tag that starts with 'v'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Read contents of release-description.txt
      - name: Read Release Description
        id: read_release_description
        run: |
          echo "::set-output name=release_notes::$(cat release-description.txt)"

      # Check the github output
      - name: Use Release Notes
        run: echo "${{ steps.read_release_description.outputs.release_notes }}"

      # Create a release using the release-description.txt content
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          prerelease: 'false'
          draft: 'false'
          body: |
            Changes in this Release:
            - First Change
            - Second Change

        #          body: ${{ env.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to authenticate the release

      # Upload the release description to the GitHub release
      - name: Add Release Description
        if: success() # Ensure the release was created successfully
        run: |
          gh release view ${{ github.ref_name }} --json url -q ".url"
          gh release edit ${{ github.ref_name }} --notes-file release-description.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}