name: CI and Release

on:
  push:
    tags:
      - 'v[0-9]+.*' # Triggers the workflow when pushing a tag that starts with 'v'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Create a release using the release-description.txt content
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          files: |
            release-description.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to authenticate the release

      # Upload the release description to the GitHub release
      - name: Add Release Description
        if: success() # Ensure the release was created successfully
        run: |
          gh release view ${{ github.ref_name }} --json url -q ".url"
          gh release edit ${{ github.ref_name }} --notes-file release-description.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}