name: run_create_files
on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-create-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step 3: Run the script
      - name: Run Python script
        run: |
          python .github/deployment/create_files.py
          echo 'current directory:'
          pwd
          echo 'ls -R:'
          ls -R

      # Step 4:
      - name: Clean up files before PR
        run: |
          rm -rf parser/yaml_combine/yaml2bpmn_converter/__pycache__/
          rm -f parser/yaml_combine/yaml_combiner.log

      - name: push changes to staging
        run: |
          git config --global user.name "github-action"
          git config --global user.email "github-action@users.noreply.github.com"

          # Add all changes (add, change, delete) made to helm/templates and other auto-generated files
          git add --force --all helm/templates/

          # Add any other changes
          git add .

          git commit -am "Auto Generated via action" || echo "Nothing to change"
          git push -u origin "${{ github.ref }}"
